### ISSUE TITLE
Generate a tabular format for data export

### ISSUE THREAD

**Issue by nuest** [weecology/ogrants#118]
Not sure if this is out of scope, but you could provide a CSV file format for all grants, in case someone wants to download the whole dataset and do some analysis.

Granted, many can probably put that together in 10 lines of script based on the YAML files, but making the data more accessible would still be nice.

**Comment by ethanwhite** [comment]
I think this would be a great addition. We already have Travis running link checks, so we could have it assemble this and push it back. Or we could assemble it as part of the Jekyll build.

**Comment by nuest** [comment]
I think it makes sense to have this as part of the Jekyll build. I would try to create a page template that effectively creates a CSV file... links to get started:

- https://idratherbewriting.com/2015/03/06/pushing-content-into-any-format-with-jekyll/
- https://learn.cloudcannon.com/jekyll/introduction-to-data-files/ (related, maybe)

**Comment by nuest** [comment]
I have a first working version as part of the eLife Sprint, see PR to the sprint repo at https://github.com/expanding-open-grants/ogrants/pull/1
