### ISSUE TITLE
master --> main 

### ISSUE THREAD

**Issue by trashbirdecology** [weecology/ogrants#126]
Rename master to main branch

**Comment by ethanwhite** [comment]
Thanks for the ping on this. It's on the To Do list for a weecology wide update, just haven't gotten there yet. Will try to get this repo more quickly.

Link to details for implementation: https://github.com/github/renaming

**Comment by ha0ye** [comment]
- [ ] copy master -> main
- [ ] check integrations (Travis is building)
  - [ ] fix errors in Travis build (broken links? #119)
- [ ] update Readme (badge links to Travis icon for master build)
- [ ] set default branch to main

**Comment by trashbirdecology** [comment]
Looks like this has been resolved?

**Comment by ethanwhite** [comment]
Yes, this is all done now. Thanks again for the suggestion @trashbirdecology!

@ha0ye  - Travis has stopped effectively supporting open source projects so I switched over the GitHub Actions instead.
