### ISSUE TITLE
Add support for listing/searching by arbitrary YAML fields

### ISSUE THREAD

**Issue by ha0ye** [weecology/ogrants#17]
e.g. using "program" to identify fellowship applications
See [twitter thread](https://twitter.com/Hao_and_Y/status/884816993152401408)

**Comment by ethanwhite** [comment]
Good descriptions for how to handle some of this here in a manner less bootstrapped than our current approach. Since we're deploying using Netlify we can use plugins if we want to.

**Comment by ethanwhite** [comment]
Thanks to @sdtaylor this is implemented for anything appearing in the the main table on the homepage.
