### ISSUE TITLE
38 more open grant proposals over at RIO

### ISSUE THREAD

**Issue by rossmounce** [weecology/ogrants#22]
Please do feel free to add those published over at RIO. 

We've got approximately 38 so far depending on what you include: https://riojournal.com/browse_journal_articles.php?form_name=filter_articles&selfurl=&backurl=&sortby=0&journal_id=17&search_hidden=&search_in_=0&search_in_hidden=&alerts_subject_cats=&alerts_sdg_cats=&from_date=&to_date=&section_type%5B%5D=181&section_type%5B%5D=177&section_type%5B%5D=174&section_type%5B%5D=183&section_type%5B%5D=178&section_type%5B%5D=234&section_type%5B%5D=235&section_type%5B%5D=176&funding_agency= 

All are openly licensed under the Creative Commons Attribution license so there are no permissions needed.

**Comment by ethanwhite** [comment]
Thanks @rossmounce - we'd definitely love to add these. FYI we're just linking to proposals and providing metadata, so no permission needed regardless, but of course I love that these are all officially OA.

If you or someone at RIO has time, PRs to add new proposals are easy and very welcome. Details on how to contribute are in the README and here: https://www.ogrants.org/add

**Comment by rossmounce** [comment]
I'll try adding some today. Might not have time to do all of them though.

**Comment by ethanwhite** [comment]
That's awesome. Thanks! Totally understand. Any help greatly appreciated. Let me know if you have any questions or run into issues as you go.

**Comment by ethanwhite** [comment]
Some of these were added by @rossmounce in #24.

**Comment by ethanwhite** [comment]
@rossmounce has finished entering all of these. What a great contribution :clap: :clap: :clap:
