### ISSUE TITLE
Grant Submission (x2)

### ISSUE THREAD

**Issue by karinorman** [weecology/ogrants#23]
---
layout: grant
title: A latent variable modeling approach to multi-taxa prediction
author: Kari Norman
year: 2016
link: https://doi.org/10.6084/m9.figshare.5198731
funder: NSF
program: Graduate Research Fellowship Program
status: funded
---

---
layout: grant
title: A latent variable modeling approach to multi-taxa prediction
author: Kari Norman
year: 2016
link: https://doi.org/10.6084/m9.figshare.5198746
funder: DOE
program: Computational Science Graduate Fellowship
status: funded
---

**Comment by ethanwhite** [comment]
Thanks @karinorman! I just added these 6eb54f018c18d8c26c38b8cd436a34022253f1d9 and they are now live on the site. There's a lot of interest in PhD fellowships so your generosity will make a lot of folks very happy.
