### ISSUE TITLE
Consider author disambiguation too?

### ISSUE THREAD

**Issue by rossmounce** [weecology/ogrants#26]
Since I mentioned funder disambiguation in https://github.com/weecology/ogrants/issues/25 , perhaps also consider the same problem for author identification. Not a problem at the moment but might become a problem as the data grows.

Add an ORCID field to the Author data?

**Comment by ethanwhite** [comment]
Good call. I've added it as a recommended field in both authors and grants and added it to mine as an example.

**Comment by ethanwhite** [comment]
@atredennick - you may want to add your ORCID to your grants if you have a few minutes. I also just added a discipline tag as well. See the new metadata examples in the README.
