### ISSUE TITLE
When was each grant made publicly available, relative to the funding call?

### ISSUE THREAD

**Issue by rossmounce** [weecology/ogrants#27]
It would be a nice optional extra to build-in and display information on when each grant was made public.

I see three distinct states:

1.) Post-award publication (likely most common)
2.) Post-submission but pre-award publication
3.) Pre-submission publication

A long term aim might be to encourage people to try opening-up at earlier stages, so making people aware of others who have opened-up earlier in the grants process would be helpful.

**Comment by ethanwhite** [comment]
My initial reaction to this is luke warm. I like the idea of encouraging more openness, but I suspect that:

1. As you suggest it will currently all be `post-award` 
2. In most cases we won't actually have this information

Given that I'm concerned about expanding the number of fields too much and thus making it seem more intimidating to add grants and easier for mistakes to creep in.

**Comment by rossmounce** [comment]
Okay for now. 

But there are some really cool stories in there e.g. Daniel Graziotin's which was pre-submission publication and Chad Hammond's which was post-submission, pre-award. Would be something to reconsider at a later date perhaps?

**Comment by ethanwhite** [comment]
Yep, that sounds good. @ctb and I both have pre-submission grants in here so I guess it's on the order of about 5% at the moment.
