### ISSUE TITLE
Move Ernest grants from original site

### ISSUE THREAD

**Issue by ethanwhite** [weecology/ogrants#3]
https://jabberwocky.weecology.org/2012/08/10/a-list-of-publicly-available-grant-proposals-in-the-biological-sciences/

**Comment by MarconiS** [comment]
I'd like to work on this issue

**Comment by ethanwhite** [comment]
Great. Thanks! Go for it.

**Comment by ethanwhite** [comment]
Done in 5a52906480515b6c69e47cea65de683ce44a72a4. Thanks @MarconiS!
