### ISSUE TITLE
Which name form to use where multiple forms exist? Permissions / Ethics?

### ISSUE THREAD

**Issue by rossmounce** [weecology/ogrants#35]
In my latest pull request I had a minor quandry with a preferred name issue.
https://github.com/weecology/ogrants/pull/33
Filing it as an issue because this might come up again in future.

Amy Robinson was co-PI on an Open Science Prize submission.
In the grant text itself she is referred to as "Amy Robinson (USA PI)", but as an author on the proposal is listed as "Amy Robinson Sterling" -- which name form to use? Perhaps we might need to ask?

**Comment by ethanwhite** [comment]
I have no objection to asking, and think that's the best way to go if we have contact information. I'm also OK with picking one and assuming that if it's important they'll contact us. In this case my guess is that the later is probably preferred with the name change happening after submission but before posting and hence the difference.

**Comment by ethanwhite** [comment]
Closing for now. We've started adding ORCID's to everything which should avoid name confusion. If we move to a more complex system we could look up name via ORCID at some point.
