### ISSUE TITLE
"Funded?" Has legitimate non-binary answers e.g. "partially"

### ISSUE THREAD

**Issue by rossmounce** [weecology/ogrants#36]
Again, sorry to add complicated detail, but I don't think "Funded?" is necessarily a binary condition in all cases.

In the case of the Open Science Prize, funding allocation was phased. Six teams got partial funding of $80,000 to help develop their projects, only one got the jackpot of $230,000 https://www.nih.gov/news-events/news-releases/open-science-prize-announces-six-team-finalists-first-phase-competition

Thus for the Open Neuroimaging Laboratory grant proposal, I put "partially funded" because $80,000 is neither "full" funding, nor no funding.

**Comment by ethanwhite** [comment]
No problem at all. I think the conversations over what to store and how are really important and requires multiple sets of perspectives and experiences to be effective.

I think the usage you've come up with is good for the metadata. I'll probably process that into the Yes category for the main table if that sounds reasonable to you, but having it in the metadata will let us do more sophisticated things with as we move forward.

**Comment by ethanwhite** [comment]
This was implemented in 5d6b8445d5c047d461bf35edfbfc8df60b01f6d6.
