### ISSUE TITLE
Trying to add my open grant

### ISSUE THREAD

**Issue by agbarnett** [weecology/ogrants#51]
---
layout: grant
title: Meta-research: Using research to increase the value of health and medical research
author: Adrian G. Barnett
ORCID: 0000-0001-6339-0374
year: 2016
link: https://eprints.qut.edu.au/98764/
funder: National Health and Medical Research Foundation
program: Senior Research Fellowship
discipline: health services research
status: funded
---

**Comment by ethanwhite** [comment]
Thanks @agbarnett! Much appreciated. Your grant is now live on the site.
