### ISSUE TITLE
and a fourth new grant to add

### ISSUE THREAD

**Issue by hpiwowar** [weecology/ogrants#71]
---
layout: grant
title: Investigating the value of automatically-gathered software impact data
author: Heather Piwowar and Jason Priem
ORCID: 0000-0003-1613-5981 and 0000-0001-6187-6610
year: 2013
link: https://doi.org/10.6084/m9.figshare.809572
funder: NSF
program: ACI-CYBERINFRASTRUCTURE, EAGER
status: funded
---

**Comment by ethanwhite** [comment]
Thanks for all of these @hpiwowar! They're all up now.
